from enum import Enum

class SudokuCandidateType(Enum):
    WITHOUT_INFERENCE_0TH_LAYER = "WITHOUT_INFERENCE_0TH_LAYER"
    NAKED_SINGLES_0TH_LAYER = "NAKED_SINGLES_0TH_LAYER"
    HIDDEN_SINGLES_0TH_LAYER = "HIDDEN_SINGLES_0TH_LAYER"
    CONSENSUS_0TH_LAYER = "CONSENSUS_0TH_LAYER"
    PARTIAL_CONSENSUS_1TH_LAYER = "PARTIAL_CONSENSUS_1TH_LAYER"
    CONSENSUS_1TH_LAYER = "CONSENSUS_1TH_LAYER"
    CONSENSUS_NTH_LAYER = "CONSENSUS_NTH_LAYER"
