from enum import Enum

class SudokuCandidateType(Enum):
    ZEROTH_LAYER_PLAIN = "ZEROTH_LAYER_PLAIN"
    ZEROTH_LAYER_NAKED_SINGLES = "ZEROTH_LAYER_NAKED_SINGLES"
    ZEROTH_LAYER_HIDDEN_SINGLES = "ZEROTH_LAYER_HIDDEN_SINGLES"
    ZEROTH_LAYER = "ZEROTH_LAYER"
    FIRST_LAYER_CONSENSUS = "FIRST_LAYER_CONSENSUS"
    NTH_LAYER = "NTH_LAYER"
