from enum import Enum

class SudokuCandidateType(Enum):
    ZEROTH_LAYER_WITHOUT_INFERENCE = "WITHOUT_INFERENCE_0TH_LAYER"
    ZEROTH_LAYER_NAKED_SINGLES = "NAKED_SINGLES_0TH_LAYER"
    ZEROTH_LAYER_HIDDEN_SINGLES = "HIDDEN_SINGLES_0TH_LAYER"
    ZEROTH_LAYER = "CONSENSUS_0TH_LAYER"
    FIRST_LAYER_PARTIAL_CONSENSUS = "PARTIAL_CONSENSUS_1TH_LAYER"
    FIRST_LAYER_CONSENSUS = "CONSENSUS_1TH_LAYER"
    NTH_LAYER = "CONSENSUS_NTH_LAYER"
