from webui.components.tables.sudoku_inference_analytics_table_component import SudokuInferenceAnalyticsTableComponent
from webui.components.tables.sudoku_table_component import SudokuTableComponent

SudokuInferenceAnalyticsTableComponent.render()
SudokuTableComponent.render()
