"""Add sudoku_image table.

Revision ID: 0b7a6714b29d
Revises: 5ea653ac1310
Create Date: 2025-11-05 03:12:11.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0b7a6714b29d"
down_revision: Union[str, Sequence[str], None] = "5ea653ac1310"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sudoku_image",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("sudoku_id", sa.Integer(), nullable=False),
        sa.Column("content", sa.LargeBinary(), nullable=False),
        sa.Column(
            "mime",
            sa.String(length=64),
            nullable=False,
            server_default="image/png",
        ),
        sa.ForeignKeyConstraint(
            ["sudoku_id"],
            ["sudoku.id"],
            name=op.f("fk_sudoku_image_sudoku_id_sudoku"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sudoku_image")),
    )
    op.create_index(
        op.f("ix_sudoku_image_sudoku_id"),
        "sudoku_image",
        ["sudoku_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_sudoku_image_sudoku_id"),
        table_name="sudoku_image",
    )
    op.drop_table("sudoku_image")
    # ### end Alembic commands ###
