"""initial

Revision ID: 5ea653ac1310
Revises: 
Create Date: 2025-11-05 02:45:33.744945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ea653ac1310'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sudoku',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('n', sa.Integer(), nullable=False),
    sa.Column('candidate_type', sa.Enum('ZEROTH_LAYER_NAKED_SINGLES', 'ZEROTH_LAYER_HIDDEN_SINGLES', 'FIRST_LAYER_CONSENSUS', name='sudokucandidatetype'), nullable=False),
    sa.Column('grid', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sudoku')
    # ### end Alembic commands ###
