"""crete_inference_succeeded_column_in_sudoku_table

Revision ID: da613b506ad9
Revises: 94ae4232f581
Create Date: 2025-11-19 15:15:42.103696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da613b506ad9'
down_revision: Union[str, Sequence[str], None] = '94ae4232f581'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sudoku', sa.Column('inference_succeeded', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sudoku', 'inference_succeeded')
    # ### end Alembic commands ###
