"""add_succeeded_and_unique_nth_layer_column_to_sudoku_inference_table

Revision ID: f4c04cfaec63
Revises: 9371bcf1d6f8
Create Date: 2025-11-23 23:45:22.027185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4c04cfaec63'
down_revision: Union[str, Sequence[str], None] = '9371bcf1d6f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sudoku_inference', sa.Column('succeeded_and_unique_nth_layer', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sudoku_inference', 'succeeded_and_unique_nth_layer')
    # ### end Alembic commands ###
