"""create_sudoku_inference_table

Revision ID: fe7d51ab54bd
Revises: 94ae4232f581
Create Date: 2025-11-20 17:32:31.963197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe7d51ab54bd'
down_revision: Union[str, Sequence[str], None] = '94ae4232f581'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sudoku_inference',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sudoku_id', sa.Integer(), nullable=False),
    sa.Column('succeeded', sa.Boolean(), nullable=False),
    sa.Column('explanation', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['sudoku_id'], ['sudoku.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sudoku_inference_sudoku_id'), 'sudoku_inference', ['sudoku_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sudoku_inference_sudoku_id'), table_name='sudoku_inference')
    op.drop_table('sudoku_inference')
    # ### end Alembic commands ###
